{{- if .Values.queue.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel_backend_helm.fullname" . }}-queue
  labels:
    {{- include "laravel_backend_helm.labels" . | nindent 4 }}
    app: laravel-backend-queue
spec:
  replicas: {{ .Values.queue.replicas }}
  selector:
    matchLabels:
      {{- include "laravel_backend_helm.selectorLabels" . | nindent 6 }}
      app: laravel-backend-queue
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel_backend_helm.labels" . | nindent 8 }}
        app: laravel-backend-queue
    spec:
      terminationGracePeriodSeconds: {{ .Values.queue.terminationGracePeriodSeconds | default 60 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel_backend_helm.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: queue-worker
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.imageBackend.repository }}:{{ .Values.imageBackend.tag }}"
          imagePullPolicy: {{ .Values.queue.imagePullPolicy }}
          command:
            {{- toYaml .Values.queue.command | nindent 12 }}
          envFrom:
            {{- with .Values.queue.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.secret.enabled }}
            {{- range .Values.secret.data }}
            - secretRef:
                name: {{ include "laravel_backend_helm.fullname" $ }}-{{ .name }}
            {{- end }}
            {{- end }}
            {{- if .Values.externalSecret.enabled }}
            - secretRef:
                name: {{ .Values.externalSecret.target.name }}
            {{- end }}
          {{- with .Values.queue.env | default list }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.queue.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.queue.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.queue.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.queue.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.queue.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
